### ISSUE TITLE
Mingw builds are failing when using latest gcc version 16.1 and old ICU library 77.1-1

### ISSUE THREAD

**Issue by bunnybot** [widelands/widelands#7028]
[<img align='left' src='https://codeberg.org/avatars/bf4ca3b86c0350e4cd4a972d9fa6ed89' alt='palino' height='48' />](https://codeberg.org/palino)*[Mirrored from Codeberg](https://codeberg.org/wl/widelands/issues/5387)*
*Created on Fri May 15 01:42:14 CEST 2026 by [**Pavol Gono (palino)**](https://codeberg.org/palino)*

---

### Describe the Bug

https://github.com/widelands/widelands/actions/runs/25844364369/job/75936334258
```
[862/867] Linking CXX executable src\ai\test\test_ai.exe
FAILED: [code=1] src/ai/test/test_ai.exe 
C:\Windows\system32\cmd.exe /C "cd . && C:\msys64\mingw64\bin\g++.exe -O3 -DNDEBUG -flto=auto -fno-fat-lto-objects -Wl,-Bstatic <@>CMakeFiles\test_ai.rsp -o src\ai\test\test_ai.exe -Wl,--out-implib,src\ai\test\libtest_ai.dll.a -Wl,--major-image-version,0,--minor-image-version,0 && cd ."
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/16.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib/libicuuc.a(umutex.ao):(.rdata$.refptr.__emutls_v._ZSt11__once_call[.refptr.__emutls_v._ZSt11__once_call]+0x0): undefined reference to `__emutls_v._ZSt11__once_call'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/16.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib/libicuuc.a(umutex.ao):(.rdata$.refptr.__emutls_v._ZSt15__once_callable[.refptr.__emutls_v._ZSt15__once_callable]+0x0): undefined reference to `__emutls_v._ZSt15__once_callable'
collect2.exe: error: ld returned 1 exit status
```

### To Reproduce

Just build inside MINGW64 with latest packages and old ICU library 77.1-1, which we are currently using

### Expected Behavior

no build failures

### Operating System

Windows 11

### Widelands Version

25a8e211d4d55129800f446915ef04a383e8c5f6

### Additional Context

I tried to find the problem with following source
```
$ cat icu-test.cc
#include <iostream>
#include <unicode/unistr.h>
int main()
{
  const icu::UnicodeString unicode_word("Hello", "UTF-8");
  std::cout << unicode_word.length() << std::endl;
  return 0;
}
```

### Older MINGW64 packages, old ICU lib - OK
```
WW930+A686861@palov-thinkpad MINGW64 ~
$ gcc -v 2>&1| tail -1
gcc version 15.2.0 (Rev13, Built by MSYS2 project)

WW930+A686861@palov-thinkpad MINGW64 ~
$ pacman -Q | grep icu
mingw-w64-x86_64-icu 77.1-1

WW930+A686861@palov-thinkpad MINGW64 ~
$ g++ -Wall icu-test.cc -licuuc

WW930+A686861@palov-thinkpad MINGW64 ~
$ ./a.exe
5
```

### Newest MINGW64 packages, newest ICU lib - OK
```
palino@LAPTOP-D7VIF73K MINGW64 ~
$ gcc -v 2>&1| tail -1
gcc version 16.1.0 (Rev3, Built by MSYS2 project)

palino@LAPTOP-D7VIF73K MINGW64 ~
$ pacman -Q | grep icu
mingw-w64-x86_64-icu 78.3-2

palino@LAPTOP-D7VIF73K MINGW64 ~
$ g++ -Wall icu-test.cc -licuuc

palino@LAPTOP-D7VIF73K MINGW64 ~
$ ./a.exe
5
```

### Newest CLANG64 packages, old ICU lib - OK
```
palino@LAPTOP-D7VIF73K CLANG64 ~
$ clang++ -v 2>&1 | head -1
clang version 22.1.4 (https://github.com/msys2/MINGW-packages 42681e05ad3617c25e48a935a48eddc72a3ac7e2)

palino@LAPTOP-D7VIF73K CLANG64 ~
$ pacman -Q | grep icu
mingw-w64-clang-x86_64-icu 77.1-1

palino@LAPTOP-D7VIF73K CLANG64 ~
$ clang++ -Wall icu-test.cc -licuuc

palino@LAPTOP-D7VIF73K CLANG64 ~
$ ./a.exe
5
```

### Newest MINGW64 packages, old ICU lib - problem
```
palino@LAPTOP-D7VIF73K MINGW64 ~
$ gcc -v 2>&1| tail -1
gcc version 16.1.0 (Rev3, Built by MSYS2 project)

palino@LAPTOP-D7VIF73K MINGW64 ~
$ pacman -Q | grep icu
mingw-w64-x86_64-icu 77.1-1

palino@LAPTOP-D7VIF73K MINGW64 ~
$ g++ -Wall icu-test.cc -licuuc

palino@LAPTOP-D7VIF73K MINGW64 ~
$ ./a.exe

palino@LAPTOP-D7VIF73K MINGW64 ~
$ echo $?
127
```
![icu_problem](/attachments/58e12c8a-7079-43f9-aea8-0827b1c37c68)

I tested also Debian sid with gcc 16.1, no issues while building widelands (except one minor warning in `src/network/network_lan_promotion.cc`).

I see two options how to continue

- trying to adapt mingw builds to newest ICU library version
- use CLANG64 for building instead of MINGW64 (but we will lose 32-bit builds and users of older Windows than 10 will probably need to additionaly install UCRT - https://learn.microsoft.com/en-us/cpp/windows/universal-crt-deployment)

**Comment by bunnybot** [comment]
[<img align='left' src='https://codeberg.org/avatars/bf4ca3b86c0350e4cd4a972d9fa6ed89' alt='palino' height='48' />](https://codeberg.org/palino)*[Mirrored from Codeberg](https://codeberg.org/wl/widelands/issues/5387#issuecomment-15001140)*
*On Fri May 15 14:21:39 CEST 2026, [**Pavol Gono (palino)**](https://codeberg.org/palino) wrote:*

---

I understand now where is the issue with newer ICU libraries than 77.1-1 - they are somehow broken in mingw:
```
palino@LAPTOP-D7VIF73K MINGW64 ~
$ gcc -v 2>&1| tail -1
gcc version 16.1.0 (Rev3, Built by MSYS2 project)

palino@LAPTOP-D7VIF73K MINGW64 ~
$ pacman -Q | grep icu
mingw-w64-x86_64-icu 78.3-2

palino@LAPTOP-D7VIF73K MINGW64 ~
$ g++ -Wall icu-test.cc -licuuc

palino@LAPTOP-D7VIF73K MINGW64 ~
$ g++ -Wall icu-test.cc /mingw64/lib/libicuuc.a /mingw64/lib/libicudt.a
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/16.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccLOIXG6.o:icu-test.cc:(.text+0x2b): undefined reference to `__imp__ZN6icu_7813UnicodeStringC1EPKcS2_'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/16.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccLOIXG6.o:icu-test.cc:(.text+0x6f): undefined reference to `__imp__ZN6icu_7813UnicodeStringD1Ev'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/16.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\ccLOIXG6.o:icu-test.cc:(.text+0x86): undefined reference to `__imp__ZN6icu_7813UnicodeStringD1Ev'
collect2.exe: error: ld returned 1 exit status
```
Dynamic linking is without problems, but static linking doesn't work.
(the last compiler options for static linking are working well with gcc 15.2 and icu 77.1-1)

I can confirm the widelands build with OPTION_BUILD_WINSTATIC=OFF is correct with newest ICU libraries.

What about bundling widelands.exe together with `/mingw64/bin/libicuuc78.dll` and `/mingw64/bin/libicudt78.dll` (even with OPTION_BUILD_WINSTATIC=ON), till the mingw static libraries are fixed?

**Comment by bunnybot** [comment]
[<img align='left' src='https://codeberg.org/avatars/593dc43e2444c25db9481960e5b693ab' alt='tothxa' height='48' />](https://codeberg.org/tothxa)*[Mirrored from Codeberg](https://codeberg.org/wl/widelands/issues/5387#issuecomment-15025383)*
*On Fri May 15 16:55:48 CEST 2026, [**Tóth András (tothxa)**](https://codeberg.org/tothxa) wrote:*

---

~If the latest version works for you, then you could try removing the version pinning from `mingw_deps` to fix the workflow builds.~ Sorry, your last comment clarifies it. Indeed, the static library problem was the reason for the pinning IIRC.

**Comment by hessenfarmer** [comment]
just came back from my holidas to see this now being broken severely, will try to elaborate a fix.
