### ISSUE TITLE
Daily builds fail with printf format error

### ISSUE THREAD

**Issue by Noordfrees** [widelands/widelands#5095]
Two of the daily PPAs are failing with the error
```
/<<PKGBUILDDIR>>/src/base/log.h:46:77: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Werror=format=]
```

This should be fixed instead of suppressed. We can then also remove again the `FORMAT_WARNINGS_(ON/OFF)` in `src/io/streamread.cc` introduced in 701fbef38c5677109dabe68252cb29c1882e8ff8.

Affected environments are:
- g++ 7.5.0, Bionic, i386 [(link)](https://launchpadlibrarian.net/565181349/buildlog_ubuntu-bionic-i386.widelands_2%3A1.1~bzr10039-202110230320~ubuntu18.04.1_BUILDING.txt.gz)
- g++ 5.4.0, Xenial, i386 [(link)](https://launchpadlibrarian.net/565181794/buildlog_ubuntu-xenial-i386.widelands_2%3A1.1~bzr10039-202110230320~ubuntu16.04.1_BUILDING.txt.gz)

On non-windows systems, we always expand the `PRIuS` macro to `lu` (for `long unsigned int`), which is correct for most systems, but on these two here, `size_t` is defined as `unsigned int` so the macro should expand to `u`. How can we distinguish between these configurations and all others in the preprocessor?

**Comment by Noordfrees** [comment]
Still fails on [Xenial](https://launchpadlibrarian.net/565522618/buildlog_ubuntu-xenial-i386.widelands_2%3A1.1~bzr10042-202110251202~ubuntu16.04.1_BUILDING.txt.gz):
```
/<<PKGBUILDDIR>>/src/base/macros.h:136:25: error: "__WORDSIZE32_SIZE_ULONG" is not defined [-Werror=undef]
```

**Comment by matthiakl** [comment]
This should not happen as of the doc in [wordsize.h](https://sources.debian.org/src/glibc/2.32-4/bits/wordsize.h/):
Either __WORDSIZE should be 64 or __WORDSIZE32_SIZE_ULONG defined to be 0 or 1.
