### ISSUE TITLE
r6943 fails to build on Ubuntu 13.10

### ISSUE THREAD

**Issue by bunnybot** [widelands/widelands#926]
Attempting to build r6943 on Ubuntu 13.10 fails with the following output:
[  5%] Building CXX object src/CMakeFiles/widelands_all.dir/wui/gamechatpanel.cc.o
/home/user/widelands/src/wui/gamechatpanel.cc: In constructor ‘GameChatPanel::GameChatPanel(UI::Panel*, int32_t, int32_t, uint32_t, uint32_t, ChatProvider&)’:
/home/user/widelands/src/wui/gamechatpanel.cc:36:23: error: ‘UINT32_MAX’ was not declared in this scope
  chat_message_counter(UINT32_MAX)
                       ^
make[2]: *** [src/CMakeFiles/widelands_all.dir/wui/gamechatpanel.cc.o] Error 1
make[1]: *** [src/CMakeFiles/widelands_all.dir/all] Error 2

Looks like UNIT32_MAX needs to be imported from somewhere other than #include <cstdint>... This was introduced when merging the branch related to bug 1304638.

Tried on Ubuntu 13.10 with GCC version 4.8.1-10ubuntu9 failed. It seems like GCC 4.8.2 on Arch managed alright though...

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2014-04-16T10:47:43Z
 * owner: hjd
 * assignee: shevonar
 * the launchpad url was https://bugs.launchpad.net/bugs/1308473

**Comment by bunnybot** [comment]
(by shevonar)
Already fixed in r6944.

**Comment by bunnybot** [comment]
(by hjd)
Great! Thanks :)

**Comment by bunnybot** [comment]
(by gunchleoc)
Fixed in build19-rc1.
