### ISSUE TITLE
Does not build with Boost 1.77

### ISSUE THREAD

**Issue by brad0** [widelands/widelands#4998]
Build testing the OpenBSD ports tree with Boost 1.77 beta1. widelands 1.0 does not build with Boost 1.77 beta1 like so..

```
/pobj/widelands-1.0/bin/c++ -DUSE_XDG -DWL_USE_GLVND -I/pobj/widelands-1.0/widelands-1.0/src -Isrc -isystem /usr/X11R6/include -isystem /usr/local/include -isystem /usr/local/include/SDL2 -O2 -pipe -DNDEBUG  -std=c++11  -DNDEBUG -DNOPARACHUTE -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-conversion -Wno-exit-time-destructors -Wno-global-constructors -Wno-padded -Wno-sign-conversion -Wno-missing-noreturn -Wno-switch-enum -Wno-weak-vtables -Wno-unreachable-code -Wno-documentation -Werror=non-pod-varargs -Qunused-arguments -Wint-to-void-pointer-cast -Winconsistent-missing-override -Werror=format-security -Werror=return-type -Werror=uninitialized -MD -MT src/network/CMakeFiles/network.dir/bufferedconnection.cc.o -MF src/network/CMakeFiles/network.dir/bufferedconnection.cc.o.d -o src/network/CMakeFiles/network.dir/bufferedconnection.cc.o -c /pobj/widelands-1.0/widelands-1.0/src/network/bufferedconnection.cc
In file included from /pobj/widelands-1.0/widelands-1.0/src/network/bufferedconnection.cc:1:
/pobj/widelands-1.0/widelands-1.0/src/network/bufferedconnection.h:313:7: error: no template named 'map' in namespace 'std'; did you mean 'max'?
        std::map<uint8_t, std::queue<std::vector<uint8_t>>> buffers_to_send_;
        ~~~~~^~~
             max
/usr/include/c++/v1/algorithm:2624:1: note: 'max' declared here
max(const _Tp& __a, const _Tp& __b, _Compare __comp)
^
In file included from /pobj/widelands-1.0/widelands-1.0/src/network/bufferedconnection.cc:1:
/pobj/widelands-1.0/widelands-1.0/src/network/bufferedconnection.h:313:7: error: non-friend class member 'max' cannot have a qualified name
        std::map<uint8_t, std::queue<std::vector<uint8_t>>> buffers_to_send_;
        ~~~~~^
/pobj/widelands-1.0/widelands-1.0/src/network/bufferedconnection.h:313:7: error: C++ requires a type specifier for all declarations
/pobj/widelands-1.0/widelands-1.0/src/network/bufferedconnection.h:313:53: error: expected ';' at end of declaration list
        std::map<uint8_t, std::queue<std::vector<uint8_t>>> buffers_to_send_;
                                                           ^
                                                           ;
/pobj/widelands-1.0/widelands-1.0/src/network/bufferedconnection.h:221:3: error: use of undeclared identifier 'buffers_to_send_'
                buffers_to_send_[priority].push(v);
                ^
/pobj/widelands-1.0/widelands-1.0/src/network/bufferedconnection.cc:213:21: error: use of undeclared identifier 'buffers_to_send_'
        for (auto& entry : buffers_to_send_) {
                           ^
6 errors generated.
```

**Comment by matthiakl** [comment]
Is there a reason, that you think boost is the problem here? The log looks more like a STL import issue, but shows nothing about boost.
Try adding `#include <map>` to the top of `src/network/bufferedconnection.h` and see whether the error changes.

**Comment by brad0** [comment]
It builds fine with Boost 1.76. It does not with 1.77. Something has changed upstream in the Boost headers.

**Comment by matthiakl** [comment]
Then please wait until Boost 1.77 is officially released. Build failures against a development version of a dependency are not necessarily bugs in our code.

**Comment by brad0** [comment]
Same issue with the final release.
