### ISSUE TITLE
Does not compile using gcc version 12.1.0-1

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands#5418]
After updating my system gcc was also updated:

~~~~
[2022-05-13T09:33:53+0200] [ALPM] upgraded gcc (11.2.0-4 -> 12.1.0-1)
[2022-05-13T09:33:57+0200] [ALPM] upgraded lib32-gcc-libs (11.2.0-4 -> 12.1.0-1)
~~~~

Compiling a release build does not work anymore after the update:

~~~~
[ 83%] Building CXX object src/ui_fsmenu/CMakeFiles/ui_fsmenu.dir/multiplayersetupgroup.cc.o
In file included from /home/kaputtnik/Quellcode/widelands-repo/widelands/src/ui_fsmenu/main.cc:30:
/home/kaputtnik/Quellcode/widelands-repo/widelands/src/editor/editorinteractive.h: In constructor 'EditorInteractive::Tools::Tools(const Widelands::Map&)':
/home/kaputtnik/Quellcode/widelands-repo/widelands/src/editor/editorinteractive.h:63:37: error: member 'EditorInteractive::Tools::unset_port_space' is used uninitialized [-Werror=uninitialized]
   63 |                      set_port_space(unset_port_space),
      |                                     ^~~~~~~~~~~~~~~~
[ 83%] Building CXX object src/ui_fsmenu/CMakeFiles/ui_fsmenu.dir/netsetup_lan.cc.o
[ 83%] Building CXX object src/ui_fsmenu/CMakeFiles/ui_fsmenu.dir/options.cc.o
cc1plus: all warnings being treated as errors
make[2]: *** [src/ui_fsmenu/CMakeFiles/ui_fsmenu.dir/build.make:398: src/ui_fsmenu/CMakeFiles/ui_fsmenu.dir/main.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:30436: src/ui_fsmenu/CMakeFiles/ui_fsmenu.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
~~~~

Compiling a debug build throws another warning as error:

~~~~
./compile.sh -a -s
…
[ 83%] Building CXX object src/base/CMakeFiles/base.dir/string.cc.o
/home/kaputtnik/Quellcode/widelands-repo/widelands/src/base/log.cc: In function 'void do_log(LogType, const Time&, const char*, ...)':
/home/kaputtnik/Quellcode/widelands-repo/widelands/src/base/log.cc:189:94: error: 'snprintf' output may be truncated before the last format character [-Werror=format-truncation=]
  189 |                 snprintf(buffer_prefix, sizeof(buffer_prefix), "[%02u:%02u:%02u.%03u %s] %s: ", hours,
      |                                                                                              ^
/home/kaputtnik/Quellcode/widelands-repo/widelands/src/base/log.cc:189:25: note: 'snprintf' output 23 or more bytes (assuming 33) into a destination of size 32
  189 |                 snprintf(buffer_prefix, sizeof(buffer_prefix), "[%02u:%02u:%02u.%03u %s] %s: ", hours,
      |                 ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  190 |                          minutes, seconds, t, gametime.is_invalid() ? "real" : "game", to_string(type));
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [src/base/CMakeFiles/base.dir/build.make:118: src/base/CMakeFiles/base.dir/log.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:6620: src/base/CMakeFiles/base.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
~~~~

Compiling using clang works.

**Comment by Noordfrees** [comment]
I'm adding g++12 to the CI in #5415 and fixing the compiler issues one by one there

**Comment by andy5995** [comment]
> After updating my system gcc was also updated:
> 

@frankystone Which Linux distro are you using?

**Comment by frankystone** [comment]
archlinux, a rolling release distribution.

Sorry for not mention it.

**Comment by mquinson** [comment]
Hello, could you point us to the relevant commits so that we can backport them in the Debian package? Failing to do so means that widelands will be removed from the "testing" rolling release in 6 days. https://tracker.debian.org/pkg/widelands

**Comment by Noordfrees** [comment]
e4da6d624640c6a9f204ec3e4a8d8d09e0158285 + 220ae30d458c8b45ea075dfca18f39d02980c3a7
If the first patch doesn't apply cleanly, the only crucial change that needs to be copied should be the one to `CMakeLists.txt`.

**Comment by mquinson** [comment]
Thanks a lot! I'll take care of this on Monday or so.

**Comment by mquinson** [comment]
Hello, for the record, I've fixed the Debian package. On that occasion, I discovered that our package version tracking thing is broken by the release of 1.0. I'm sorry for not packaging it earlier, but I'm now on it. I should upload it later today.

But that's not the reason why I'm writing now. I wanted to signal that -Werror does not sound like a good idea in release settings: users most probably don't want to have a breakage just because of a warning. I think that -Werror should be reserved to debug and developers builds, if possible.

Thanks for your time,
Mt
