### ISSUE TITLE
Trunk r6970 does not compile on Ubuntu

### ISSUE THREAD

**Issue by bunnybot** [widelands/widelands#934]
I get the build error below on Ubuntu 14.04 with gcc 4.8.

bool luna_table_has_key(lua_State* L, const std::string& key); is defined in luna_impl.h:55, so I have no idea what the problem is.

It's a fresh Ubuntu install, so I double-checked with one of the brances I'm working on to make sure it's not just a problem with my setup.

[ 83%] Building CXX object src/scripting/test/CMakeFiles/test_widelands_scripting.dir/__/__/build_info.cc.o
Linking CXX executable test_widelands_scripting
../liberis.a(loslib.c.o): In function `os_tmpname':
/home/bratzbert/sources/widelands/test/src/scripting/eris/loslib.c:108: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `void m_register_properties_in_metatable<L_Class, L_Class>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:297: undefined reference to `luna_table_has_key(lua_State*, std::string const&)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `void m_register_methods_in_metatable<L_Class, L_Class>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:336: undefined reference to `luna_table_has_key(lua_State*, std::string const&)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `void m_register_properties_in_metatable<L_SubClass, L_SubClass>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:297: undefined reference to `luna_table_has_key(lua_State*, std::string const&)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `void m_register_methods_in_metatable<L_SubClass, L_SubClass>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:336: undefined reference to `luna_table_has_key(lua_State*, std::string const&)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `void m_register_properties_in_metatable<L_SubClass, L_Class>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:297: undefined reference to `luna_table_has_key(lua_State*, std::string const&)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o:/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:336: more undefined references to `luna_table_has_key(lua_State*, std::string const&)' follow
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `int m_persist<L_Class>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:258: undefined reference to `luna_unpersisting_closure(lua_State*)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `int m_property_dispatch<L_Class, L_Class>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:141: undefined reference to `report_error(lua_State*, char const*, ...)'
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:155: undefined reference to `report_error(lua_State*, char const*, ...)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `int m_method_dispatch<L_Class, L_Class>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:172: undefined reference to `report_error(lua_State*, char const*, ...)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `int m_persist<L_SubClass>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:258: undefined reference to `luna_unpersisting_closure(lua_State*)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `int m_property_dispatch<L_SubClass, L_SubClass>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:141: undefined reference to `report_error(lua_State*, char const*, ...)'
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:155: undefined reference to `report_error(lua_State*, char const*, ...)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `int m_method_dispatch<L_SubClass, L_SubClass>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:172: undefined reference to `report_error(lua_State*, char const*, ...)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `int m_property_dispatch<L_SubClass, L_Class>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:141: undefined reference to `report_error(lua_State*, char const*, ...)'
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:155: undefined reference to `report_error(lua_State*, char const*, ...)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o:/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:172: more undefined references to `report_error(lua_State*, char const*, ...)' follow
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `int m_persist<L_VirtualClass>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:258: undefined reference to `luna_unpersisting_closure(lua_State*)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `int m_property_dispatch<L_VirtualClass, L_VirtualClass>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:141: undefined reference to `report_error(lua_State*, char const*, ...)'
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:155: undefined reference to `report_error(lua_State*, char const*, ...)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `int m_method_dispatch<L_VirtualClass, L_VirtualClass>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:172: undefined reference to `report_error(lua_State*, char const*, ...)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `int m_property_dispatch<L_VirtualClass, L_Class>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:141: undefined reference to `report_error(lua_State*, char const*, ...)'
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:155: undefined reference to `report_error(lua_State*, char const*, ...)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o:/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:172: more undefined references to `report_error(lua_State*, char const*, ...)' follow
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `int m_persist<L_MultiClass>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:258: undefined reference to `luna_unpersisting_closure(lua_State*)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `int m_property_dispatch<L_MultiClass, L_MultiClass>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:141: undefined reference to `report_error(lua_State*, char const*, ...)'
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:155: undefined reference to `report_error(lua_State*, char const*, ...)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `int m_method_dispatch<L_MultiClass, L_MultiClass>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:172: undefined reference to `report_error(lua_State*, char const*, ...)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `int m_property_dispatch<L_MultiClass, L_Class>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:141: undefined reference to `report_error(lua_State*, char const*, ...)'
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:155: undefined reference to `report_error(lua_State*, char const*, ...)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o:/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:172: more undefined references to `report_error(lua_State*, char const*, ...)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [src/scripting/test/test_widelands_scripting] Error 1
make[1]: *** [src/scripting/test/CMakeFiles/test_widelands_scripting.dir/all] Error 2
make: *** [all] Error 2

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2014-05-31T06:59:31Z
 * owner: gunchleoc
 * the launchpad url was https://bugs.launchpad.net/bugs/1325170

**Comment by bunnybot** [comment]
(by hjd)
Thanks for reporting this issue.

I'm a bit puzzled, since it works fine on my local 14.04 machine and it built without problems in the daily PPA https://code.launchpad.net/~widelands-dev/+recipe/widelands-daily. (The 12.10 build failures are presumably a separate issue, see comment #3 on bug 1318315 for details.)

Are you building from scratch or updating an existing build (for instance with ./update.sh)?

**Comment by bunnybot** [comment]
(by gunchleoc)
I was building from scratch:

cd trunk
bzr pull
cd ..
bzr branch trunk test
cd test
./compile.sh

I also compared luna_impl.h with the branch that does compile, and the files are identical.

I then deleted trunk and got a new copy from Launchpad to make sure I don't have a case of corrupted data, but the error still happens. *headdesk*

**Comment by bunnybot** [comment]
(by sirver)
Two ideas here: 

1) Try removing the ifdefs in c_utils.h here:

#ifdef __GNUC__
void report_error(lua_State*, const char*, ...)
	__attribute__((__format__(__printf__, 2, 3), noreturn));
#else
void report_error [[noreturn]] (lua_State*, const char*, ...)
#endif

and only keep the second case:

void report_error [[noreturn]] (lua_State*, const char*, ...)

2) rename c_utils.h to widelands_c_utils.h to make sure the name of the include is unique across the system and see if this fixes anything.

**Comment by bunnybot** [comment]
(by gunchleoc)
Idea 1) gives me:

[ 83%] Building CXX object src/scripting/test/CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o
In file included from /home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:29:0,
                 from /home/bratzbert/sources/widelands/test/src/scripting/luna.h:63,
                 from /home/bratzbert/sources/widelands/test/src/scripting/test/test_luna.cc:26:
/home/bratzbert/sources/widelands/test/src/scripting/c_utils.h:44:1: error: expected initializer before ‘inline’
 inline void lua_pushstring (lua_State * L, const std::string & s) {
 ^
In file included from /home/bratzbert/sources/widelands/test/src/scripting/luna.h:63:0,
                 from /home/bratzbert/sources/widelands/test/src/scripting/test/test_luna.cc:26:
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h: In function ‘int m_dispatch_property_in_metatable(lua_State*, bool)’:
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:75:66: error: there are no arguments to ‘report_error’ that depend on a template parameter, so a declaration of ‘report_error’ must be available [-fpermissive]
    report_error(L, "invalid property without dispatcher function");
                                                                  ^
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:75:66: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h: In function ‘int m_property_dispatch(lua_State*)’:
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:141:68: error: there are no arguments to ‘report_error’ that depend on a template parameter, so a declaration of ‘report_error’ must be available [-fpermissive]
   report_error(L, "Property needs at least the object as argument!");
                                                                    ^
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:155:49: error: there are no arguments to ‘report_error’ that depend on a template parameter, so a declaration of ‘report_error’ must be available [-fpermissive]
   report_error(L, "The property is read-only!\n");
                                                 ^

etc...

======================================================

Idea 2) gives me:

[ 83%] Building CXX object src/scripting/test/CMakeFiles/test_widelands_scripting.dir/__/__/build_info.cc.o
Linking CXX executable test_widelands_scripting
../liberis.a(loslib.c.o): In function `os_tmpname':
/home/bratzbert/sources/widelands/test/src/scripting/eris/loslib.c:108: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `void m_register_properties_in_metatable<L_Class, L_Class>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:297: undefined reference to `luna_table_has_key(lua_State*, std::string const&)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `void m_register_methods_in_metatable<L_Class, L_Class>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:336: undefined reference to `luna_table_has_key(lua_State*, std::string const&)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `void m_register_properties_in_metatable<L_SubClass, L_SubClass>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:297: undefined reference to `luna_table_has_key(lua_State*, std::string const&)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `void m_register_methods_in_metatable<L_SubClass, L_SubClass>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:336: undefined reference to `luna_table_has_key(lua_State*, std::string const&)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `void m_register_properties_in_metatable<L_SubClass, L_Class>(lua_State*)':
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:297: undefined reference to `luna_table_has_key(lua_State*, std::string const&)'
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o:/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:336: more undefined references to `luna_table_has_key(lua_State*, std::string const&)' follow
CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o: In function `int m_persist<L_Class>(lua_State*)':

etc...

**Comment by bunnybot** [comment]
(by sirver)
okay, so 2) did not help at all.

1) seems like progress... kinda. Remove all inline in c_util? 

the whole issue is very weird. Can you compile with gcc 4.7?

**Comment by bunnybot** [comment]
(by gunchleoc)
Just for kicks, I tried compiling on a different machine with Trusty 32 bit, and I get the exact same problem.

What do you mean by "Remove all inline in c_util?"

Output of gcc 4.7:

[ 83%] Building CXX object src/scripting/test/CMakeFiles/test_widelands_scripting.dir/test_luna.cc.o
In file included from /home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:29:0,
                 from /home/bratzbert/sources/widelands/test/src/scripting/luna.h:63,
                 from /home/bratzbert/sources/widelands/test/src/scripting/test/test_luna.cc:26:
/home/bratzbert/sources/widelands/test/src/scripting/widelands_c_utils.h:36:21: error: ‘noreturn’ was not declared in this scope
/home/bratzbert/sources/widelands/test/src/scripting/widelands_c_utils.h: In lambda function:
/home/bratzbert/sources/widelands/test/src/scripting/widelands_c_utils.h:36:30: error: expected ‘{’ before ‘]’ token
/home/bratzbert/sources/widelands/test/src/scripting/widelands_c_utils.h: At global scope:
/home/bratzbert/sources/widelands/test/src/scripting/widelands_c_utils.h:44:1: error: expected initializer before ‘inline’
In file included from /home/bratzbert/sources/widelands/test/src/scripting/luna.h:63:0,
                 from /home/bratzbert/sources/widelands/test/src/scripting/test/test_luna.cc:26:
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h: In function ‘int m_dispatch_property_in_metatable(lua_State*, bool)’:
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:75:66: error: there are no arguments to ‘report_error’ that depend on a template parameter, so a declaration of ‘report_error’ must be available [-fpermissive]
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:75:66: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h: In function ‘int m_property_dispatch(lua_State*)’:
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:141:68: error: there are no arguments to ‘report_error’ that depend on a template parameter, so a declaration of ‘report_error’ must be available [-fpermissive]
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h:155:49: error: there are no arguments to ‘report_error’ that depend on a template parameter, so a declaration of ‘report_error’ must be available [-fpermissive]
/home/bratzbert/sources/widelands/test/src/scripting/luna_impl.h: In function ‘int m_method_dispatch(lua_State*)’:

etc...

**Comment by bunnybot** [comment]
(by sirver)
can you try a release build? It does not build tests, so we'll figure out if it has something to do with link order.

**Comment by bunnybot** [comment]
(by gunchleoc)
Release mode with gcc 4.8.2:

[100%] Building CXX object src/CMakeFiles/widelands.dir/build_info.cc.o
Linking CXX executable widelands
CMakeFiles/widelands.dir/main.cc.o: In function `main':
main.cc:(.text.startup+0x1cc): undefined reference to `WLApplication::get(int, char const**)'
main.cc:(.text.startup+0x1d7): undefined reference to `WLApplication::run()'
main.cc:(.text.startup+0x1eb): undefined reference to `WLApplication::~WLApplication()'
main.cc:(.text.startup+0x303): undefined reference to `WLApplication::show_usage()'
main.cc:(.text.startup+0x310): undefined reference to `WLApplication::~WLApplication()'
main.cc:(.text.startup+0x4a0): undefined reference to `WLApplication::~WLApplication()'
CMakeFiles/widelands.dir/main.cc.o:(.gcc_except_table+0x5c): undefined reference to `typeinfo for _wexception'
collect2: error: ld returned 1 exit status
make[2]: *** [src/widelands] Error 1
make[1]: *** [src/CMakeFiles/widelands.dir/all] Error 2
make: *** [all] Error 2

**Comment by bunnybot** [comment]
(by gunchleoc)
Same with gcc 4.7

**Comment by bunnybot** [comment]
(by gunchleoc)
Cuiouser and curiouser... I did some more fiddling and had a look at my branch https://code.launchpad.net/~widelands-dev/widelands/bug-1293158

This branch is base on trunk version  6970, and I did the exact same fix as 6971 and did some changes in the strintg output in src/editor/tools/editor_info_tool.cc and it will compile without problems.

I deleted the branch and grabbed a new version; it still compiles.

So, I compared the compiler output - trunk simply skips compiling Widelands at all! So, of course there is nothingt to link.

Trunk output:
===========

Linking C static library liberis.a
[ 83%] Built target eris
Scanning dependencies of target widelands_all
Linking CXX static library libwidelands_all.a
[ 83%] Built target widelands_all
Scanning dependencies of target test_widelands_scripting
[ 83%] Building CXX object src/scripting/test/CMakeFiles/test_widelands_scripting.dir/scripting_test_main.cc.o


Working branch output:
===================

Linking C static library liberis.a
[  5%] Built target eris
Scanning dependencies of target widelands_all
[  6%] Building CXX object src/CMakeFiles/widelands_all.dir/map_generator.cc.o

Trunk also has an extra line in the CMake output:

You have called ADD_LIBRARY for library widelands_all without any source files. This typically indicates a problem with your CMakeLists.txt file

**Comment by bunnybot** [comment]
(by gunchleoc)
And here's the branch outout

**Comment by bunnybot** [comment]
(by sirver)
You have called ADD_LIBRARY for library widelands_all without any source
files. This typically indicates a problem with your CMakeLists.txt file

This must be it. In trunk, src/CMakeLists.txt, line 60 the call is made. It uses WL_SRCS_CC which is set a few lines above using a recursive glob. Maybe that fails for some reasons? New cmake version?

**Comment by bunnybot** [comment]
(by gunchleoc)
I am compiling both trunk and the working branch on the same computer, src/CMakeLists.txt is identical in both, CMakeLists.txt as well.

cmake version 2.8.12.2

BTW the branch I am successfully compiling is https://code.launchpad.net/~widelands-dev/widelands/bug-1293158 which is almost identical to trunk.  I did a full compare with Meld just to be sure, and the only difference between the files is a blank line in cmd_queue.h and my changes in editor_info_tool.cc

**Comment by bunnybot** [comment]
(by sirver)
there is also a include of stdint.h that is different between those branches. Maybe it is that? Seems pretty weird though....

You could try starting from the branch that compiles and copying the changed files over one by one and see if this will fail eventually.

**Comment by bunnybot** [comment]
(by gunchleoc)
No, that's not it. I added the stdint.h include to my branch as well, because without it, it wouldn't compile anyway ;)

I have now deleted all the files in trunk with Nautilus (while not showing the hidden files) and copied the content of the branch over. It still skips the compilation.

If I merge trunk into a working branch, it will compile. So, I guess that's what I need to do for now whenever I want to create a new branch - instead of branching from trunk, branch from a working branch that has minimal changes in it, then merge trunk into it and then start working.

**Comment by bunnybot** [comment]
(by gunchleoc)
The problem seems to have resolved itself
