### ISSUE TITLE
trunk 7650 fails to compile on gcc 5.2.0

### ISSUE THREAD

**Issue by bunnybot** [widelands/widelands#3068]
c:/data/bzr/widelands/working/src/logic/production_program.cc: In member function 'virtual void Widelands::ProductionProgram::ActProduce::execute(Widelands::Game&, Widelands::ProductionSite&) const':
c:/data/bzr/widelands/working/src/logic/production_program.cc:1071:26: error: 'count' may be used uninitialized in this function [-Werror=maybe-uninitialized]   (boost::format(ngettext("Produced %s", "Produced %s", count)) % ware_list).str();
                          ^
c:/data/bzr/widelands/working/src/logic/production_program.cc: In member function 'virtual void idelands::ProductionProgram::ActRecruit::execute(Widelands::Game&, Widelands::ProductionSite&) const':
c:/data/bzr/widelands/working/src/logic/production_program.cc:1167:26: error: 'c
ount' may be used uninitialized in this function [-Werror=maybe-uninitialized]   (boost::format(ngettext("Recruited %s", "Recruited %s", count)) % unit_string).str();
                          ^
cc1plus.exe: some warnings being treated as errors
ninja: build stopped: subcommand failed.

We set -Werror=uninitialized in CMakeList.txt, i am not sure if this implicits -Wmaybe-uninitialized?

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-11-28T20:15:24Z
 * owner: tino79
 * the launchpad url was https://bugs.launchpad.net/bugs/1520820

**Comment by bunnybot** [comment]
(by gunchleoc)
Fixed in build19-rc1.
