### ISSUE TITLE
FTBFS with GCC 5

### ISSUE THREAD

**Issue by bunnybot** [widelands/widelands#970]
The current in-development version of GCC is 5.0, which I believe is scheduled for release later this year. Debian has already started testing with experimental snapshot packages to assess how many packages in their archive will require patches to support this new version. I figuered I'd test how it coped with the current development version of Widelands since it sounds likely that the new GCC version will be released either before or shortly after build19.

I used the Debian experimental package [1] mentioned above, more specifically version 5-20150307-1 to attempt to build r7428.

The build was invoked in the following way:
$ cmake -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 ..
$ make

This failed while compiling src/wui/CMakeFiles/wui_chat_ui.dir/chat_msg_layout.cc, see attached log for details.

I haven't looked into other build failures with GCC 5, but I hope it is possible to resolve this in a backwards compatible way so that we will still be able to build with older versions as well.

If you have patches or suggestions, just let me know and I'll try them out. Since it broke so early in the build process I have a hunch there may be more problems later on as well.

[1] https://tracker.debian.org/pkg/gcc-5

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-03-15T11:45:59Z
 * owner: hjd
 * the launchpad url was https://bugs.launchpad.net/bugs/1432339

**Comment by bunnybot** [comment]
(by hjd)

**Comment by bunnybot** [comment]
(by hjd)
Sorry, false alarm.

I just tried with a newer snapshot (5-20150316-1 ), and managed to build r7428 without any issues. I'll keep an eye open and check back from time to time, though.

**Comment by bunnybot** [comment]
(by hjd)
GCC 5.1 has been released and packaged in Debian Unstable. I tried to build with 5.1.1-3 now, but ran into the following issue:
[  3%] Building CXX object src/scripting/test/CMakeFiles/test_scripting.dir/test_luna.cc.o
Linking CXX executable test_scripting
../../third_party/libthird_party_eris.a(loslib.c.o): In function `os_tmpname':
/home/debian/widelands/src/third_party/eris/loslib.c:108: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
CMakeFiles/test_scripting.dir/test_luna.cc.o: In function `boost::unit_test::make_test_case(boost::unit_test::callback0<boost::unit_test::ut_detail::unused> const&, boost::unit_test::basic_cstring<char const>)':
/usr/include/boost/test/unit_test_suite_impl.hpp:255: undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name[abi:cxx11](boost::unit_test::basic_cstring<char const>)'
collect2: error: ld returned 1 exit status
src/scripting/test/CMakeFiles/test_scripting.dir/build.make:120: recipe for target 'src/scripting/test/test_scripting' failed
make[2]: *** [src/scripting/test/test_scripting] Error 1
CMakeFiles/Makefile2:27271: recipe for target 'src/scripting/test/CMakeFiles/test_scripting.dir/all' failed
make[1]: *** [src/scripting/test/CMakeFiles/test_scripting.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2


However, the problem here seems to be in boost-test with a version which was built with an earlier GCC release. For those who don't know, Debian has been in a freeze for quite some time, but now that Debian 8.0 was recently released, I expect development and packaging of newer versions to pick up pace. I therefore expect we will have a new boost version not far into the future, and will keep an eye out in case we still have problems then. From what I can see the default compiler i still GCC4.9, so there might be a larger transition planned before switching to GCC 5.1.

**Comment by bunnybot** [comment]
(by hjd)
Problem has gone away again in gcc-5 5.1.1-5, allowing me to post bug 1455763.

**Comment by bunnybot** [comment]
(by nasenbaer)
as the bug was set to invalid, i removed it from milestone build19-rc1 - just cleanup ;)
